Repository AY2425S2-CS2113-T11b-2/tp, pull requests merged in 2025-04, with the labels that each got.

#75 modify UserData to store custom mods
  data/user.txt
  src/main/java/seedu/duke/data/UserData.java
  src/main/java/seedu/duke/data/UserMod.java
Labels: priority.Medium

#79 added DG template
  docs/DeveloperGuide.md
Labels: priority.Medium, priority.Low

#82 added DG Content
  docs/DeveloperGuide.md
Labels: priority.Low

#89 added DG and UG
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/assets/GrandRhombus.png
Labels: priority.High

#95 last edits DG Table of contents
  docs/DeveloperGuide.md
Labels: priority.Low

#111 Format specialisation table
  src/main/java/seedu/duke/command/Specialisation.java
Labels: priority.Medium

#117 Fix /grad table formatting
  src/main/java/seedu/duke/command/ViewGradRequirements.java
Labels: priority.Medium

#118 Fix table formatting of /grad
  src/main/java/seedu/duke/command/AddCustomModule.java
  src/main/java/seedu/duke/command/AddUserModule.java
  src/main/java/seedu/duke/command/ViewGradRequirements.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: severity.Low

#173 Fix /workload to only allow at most 1 argument
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/AddCustomModule.java
  src/main/java/seedu/duke/command/ViewGradRequirements.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: severity.Medium

#174 Fix /view to only allow at most 1 parameter and must be integer between 1 and 8
  src/main/java/seedu/duke/CommandParser.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: severity.Medium

#178 Fix /help command arguments
  src/main/java/seedu/duke/command/Help.java
Labels: priority.High

#179 Fix program shutting down with no user input
  src/main/java/seedu/duke/CommandParser.java
Labels: priority.High, severity.Medium

#183 Fix argument spacing in Command Parser
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/AddCustomModule.java
  src/main/java/seedu/duke/command/DetailModules.java
  src/main/java/seedu/duke/data/GradModuleList.java
  src/main/java/seedu/duke/data/UserMod.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: priority.High, severity.Medium

#186 Add JavaDoc Comments for Workload & Grad
  src/main/java/seedu/duke/command/ViewGradRequirements.java
  src/main/java/seedu/duke/command/Workload.java
Labels: priority.Medium

#194 Fix /schedule arguments and display
  docs/UserGuide.md
  docs/team/itsjoelha.md
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/Help.java
  src/main/java/seedu/duke/command/RecommendedSchedule.java
  src/main/java/seedu/duke/errors/ErrorHandler.java
Labels: priority.High
