Repository AY2425S2-CS2113-T11b-2/tp, pull requests merged in 2025-03, with the labels that each got.

#12 Add CommandParser class and detects input
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Specialisation.java
Labels: priority.High

#15 Fix specialisation command
  src/main/java/seedu/duke/CommandParser.java
Labels: priority.High

#17 Fix specialisation line spacing
  src/main/java/seedu/duke/Specialisation.java
Labels: type.Task, priority.High

#18 Add try catch to commandparser
  src/main/java/seedu/duke/Duke.java
Labels: type.Task, priority.High

#27 Implemented Reccomended Schedule
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ListModules.java
  src/main/java/seedu/duke/command/RecommendedSchedule.java
  src/main/java/seedu/duke/data/GradModuleList.java
Labels: priority.High

#28 Implemented View Graduation Requirements
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Help.java
  src/main/java/seedu/duke/command/RecommendedSchedule.java
  src/main/java/seedu/duke/command/ViewGradRequirements.java
  src/main/java/seedu/duke/data/Data.java
  src/main/java/seedu/duke/data/GradModuleList.java
  src/main/java/seedu/duke/data/Mod.java
  src/test/java/seedu/duke/CommandParserTest.java
  src/test/java/seedu/duke/command/AddModuleTest.java
  src/test/java/seedu/duke/command/DeleteModuleTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#29 Gradle Bug Fixing
  META-INF/MANIFEST.MF
  src/main/java/seedu/duke/command/AddModule.java
  src/main/java/seedu/duke/command/DetailModules.java
  src/main/java/seedu/duke/data/MasterModuleList.java
  src/main/java/seedu/duke/data/Mod.java
  src/main/java/seedu/duke/errors/ErrorHandler.java
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/moduledata.txt
Labels: priority.High

#38 Add more JUnit Tests & Assertions
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/Help.java
  src/main/java/seedu/duke/command/Specialisation.java
  src/main/java/seedu/duke/errors/ErrorHandler.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: type.Task

#39 Implement View Module Workload for Semester
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/AddMod.java
  src/main/java/seedu/duke/command/DeleteMod.java
  src/main/java/seedu/duke/command/Help.java
  src/main/java/seedu/duke/command/Workload.java
  src/main/java/seedu/duke/data/GradModuleList.java
  src/main/java/seedu/duke/data/MasterModuleList.java
  src/main/java/seedu/duke/data/Mod.java
  src/main/resources/moduledata.txt
  src/test/java/seedu/duke/CommandParserTest.java
Labels: type.Story, priority.High

#51 Refactor code for exit & help commands
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/DeleteMod.java
  src/main/java/seedu/duke/command/Help.java
  src/main/java/seedu/duke/data/Mod.java
  src/test/java/seedu/duke/CommandParserTest.java
  text-ui-test/input.txt
Labels: type.Task, priority.Medium

#52 Fix table formatting for Detail Modules
  src/main/java/seedu/duke/command/DetailModules.java
  src/main/java/seedu/duke/data/Mod.java
Labels: priority.Medium

#53 Added User class
  src/main/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddUserModule.java
  src/main/java/seedu/duke/command/DeleteModule.java
  src/main/java/seedu/duke/command/DeleteUserModule.java
  src/main/java/seedu/duke/command/ListModules.java
  src/main/java/seedu/duke/data/EducationLevel.java
  src/main/java/seedu/duke/data/Grade.java
  src/main/java/seedu/duke/data/User.java
  src/main/java/seedu/duke/data/UserMod.java
  src/test/java/seedu/duke/CommandParserTest.java
  src/test/java/seedu/duke/command/AddModuleTest.java
  src/test/java/seedu/duke/command/AddUserModuleTest.java
  src/test/java/seedu/duke/command/DeleteModuleTest.java
  src/test/java/seedu/duke/command/DeleteUserModuleTest.java
Labels: priority.High

#54 added SU fucntionality - command = /su
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/SuUserModule.java
  src/main/java/seedu/duke/data/User.java
Labels: priority.Medium

#56 bug fix for /grade and /view
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/ListModules.java
  src/main/java/seedu/duke/data/Grade.java
  src/main/java/seedu/duke/data/UserMod.java
Labels: priority.High

#59 /su print bug
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/SuUserModule.java
Labels: priority.High

#67 delete old Add & Delete
  src/main/java/seedu/duke/command/AddMod.java
  src/main/java/seedu/duke/command/DeleteMod.java
  src/main/java/seedu/duke/command/DeleteModule.java
Labels: type.Bug, priority.High

#68 Update Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High

#69 Fix duplicated print statements
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/command/AddUserModule.java
  src/main/java/seedu/duke/command/DeleteUserModule.java
  src/test/java/seedu/duke/CommandParserTest.java
Labels: priority.High
